cart/urls.py
from django.urls import path
from .views import (
cart_home, 
cart_update, 
checkout_home,
)

urlpatterns = [
    path('', cart_home, name='home'),
    path('update', cart_update, name='update'),
    path('checkout', checkout_home, name='checkout'),
    
]

product/urls.py
#from django.contrib import admin
from django.urls import path
#from django.urls import url
#from django.conf import settings
#from django.conf.urls.static import static
from product.views import (
ProductDetailSlugView,
ProductListView,
#list_view,
#ProductDetailView,
#Detail_view,
#ProductFeaturedDetailView, 
#ProductFeaturedListView,
)

urlpatterns = [
    path('', ProductListView.as_view(), name='list'),
    path('<slug:slug>/', ProductDetailSlugView.as_view(), name='detail'),
    #path('products-f/<int:pk>', Detail_view),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from home.views import (home_page,
view, 
login_page, 
_logout,
register_page,
)
from product.views import (
ProductDetailSlugView,
#ProductListView,
#list_view,
#ProductDetailView,
#Detail_view,
#ProductFeaturedDetailView, 
#ProductFeaturedListView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include(("product.urls", "products"), namespace='products')),
    path('bootstrap/', TemplateView.as_view(template_name='bootstrap/example.html')),
    path('search/', include(("search.urls", "search"), namespace='search')),
    path('cart/', include(("cart.urls", "cart"), namespace='cart')),
    path('home/', home_page, name='home'),
    path('view/', view, name='view'),
    path('login/', login_page, name='login'), 
    path('', home_page, name='home'),
    path('logout/', _logout, name='logout'), 
    path('register/', register_page, name='register'), 
    

    #path('featured/<int:pk>', ProductFeaturedDetailView.as_view()),
    #path('featured/', ProductFeaturedListView.as_view()),
    #path('products-f/', list_view),
    #path('products/<int:pk>', ProductDetailView.as_view()),
    #path('products/<slug:slug>', ProductDetailSlugView.as_view()),
    #path('products-f/<int:pk>', Detail_view),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

product/models.py
import os
import random
from django.db import models
from django.db.models.signals import pre_save, post_save
from project.utils import unique_slug_generator
from django.urls import reverse

def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext
  
class ProductManager(models.Manager):
    def featured(self):
        return self.get_queryset().filter(featured = True)

    def get_by_id(self, id):
        qs =  self.get_queryset().filter(id=id)
        if qs.count() == 1:
            return qs.first()
        return None

def upload_image_path(instance, filename):
    #print(filename)
    new_filename = random.randint(1, 45165615151)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename = new_filename, ext=ext)
    return "products/{new_filename}/{final_filename}".format(new_filename=new_filename, final_filename=final_filename)

    #print(instance)
# Create your models here.
class Product(models.Model):
    title       = models.CharField(max_length=120)
    slug        = models.SlugField(unique=True, null=True, blank=True)
    description = models.TextField()
    price       = models.DecimalField(decimal_places=2, max_digits=20, default=40)
    image       = models.ImageField(upload_to='products/', null=True, blank=True)
    featured    = models.BooleanField(default=False)

    objects = ProductManager()

    def get_absolute_url(self):
        #return "/products/{slug}/".format(slug=self.slug)
        return reverse("products:detail", kwargs={"slug":self.slug})


    def __str__(self):
        return self.title

    def __unicode__(self):
        print("hello")
        return self.title

    @property
    def name(self):
        return self.title

def product_pre_save_reciever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_reciever, sender=Product)

product/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from cart.models import Cart
# Create your views here.

from .models import Product

class ProductDetailSlugView(DetailView):
    queryset = Product.objects.all()
    template_name = "products/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailSlugView, self).get_context_data(*args, **kwargs)
        cart_obj, new_obj = Cart.objects.new_or_get(self.request)
        context['cart'] = cart_obj
        return context

    def get_object(self, *args, **kwargs):
        request = self.request
        slug = self.kwargs.get('slug')
        #instance = get_object_or_404(Product, slug=slug)
        try:
             instance = get_object_or_404(Product, slug=slug)
        except Product.DoesNotExist:
            raise Http404("Not found..")
        except Product.MultipleObjectsReturned:
            qs = Product.objects.filter(slug=slug, active=True)
            instance = qs.first()
        except:
            raise Http404("achaaaa")
        return instance
        
class ProductFeaturedListView(ListView):
    template_name = "products/list.html"

    def get_queryset(self, *args, **kwargs):
            request  = self.request
            return Product.objects.featured()

class ProductFeaturedDetailView(DetailView):
    template_name = "products/detail.html"

    def get_queryset(self, *args, **kwargs):
            request  = self.request
            return Product.objects.featured()


class ProductListView(ListView):
    queryset = Product.objects.all()
    template_name = "products/list.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductListView, self).get_context_data(*args, **kwargs)
        print(context)
        return context
        # return render(self.request, "products/list.html", context)

def list_view(request):
    queryset = Product.objects.all()
    context = {
        'object_list': queryset
    }
    return render(request, "products/list.html", context)

class ProductDetailView(DetailView):
    queryset = Product.objects.all()
    template_name = "products/detail.html"

    def get_context_data(self, *args, **kwargs):
        context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
        print(context)
        return context
    
    def get_object(self, *args, **kwargs):
        request = self.request
        pk = self.kwargs.get('pk')
        instance = Product.objects.get_by_id(pk)
        if instance is None:
            raise Http404("Product doesn't exist")
        return instance
    
def Detail_view(request, pk, *args, **kwargs):
    #instance = Product.objects.all()
    #instance = get_object_or_404(Product, pk=pk)
    #try:
    #   instance  = Product.objects.get(id=pk)
    #except Product.DoesNotExist:
    #    print('no product here')
     #   raise Http404("product does not exist")
    #except:
     #   print("huh?")

    instance = Product.objects.get_by_id(id=pk)
    #print(instance)
    if instance is None:
        raise Http404("product does not exist")
    #qs = Product.objects.filter(id=pk)
    #if qs.exists() and qs.count() == 1:
    #    instance = qs.first()
    #else:
    #    raise Http404("faltu ki majgadmari nahi karne ka")
    context = {
        'object': instance
    }
    return render(request, "products/detail.html", context)

product/templates/base/css.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

product/templates/base/js.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

product/templates/base/navbar.html
{% url 'cart:home' as cart_url %}
<nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="navbar-brand" href="#">
          <img src="https://cdn.vectorstock.com/i/1000x1000/27/86/people-shopping-bag-color-logo-vector-4122786.jpg" width="30" height="30"
            class="d-inline-block align-top" alt="">
          Shopify
        </a>
        <button class="navbar-toggler" type="button" data-toggle='collapse' data-target='#navbarCollapseLinks'
          aria-expanded="false" aria-label="Toggle Navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapseLinks">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a href="/home" class="nav-link">Home</a>
            </li>
            <li class="nav-item">
              <a href="/products" class="nav-link">Products</a>
            </li>
            <li class="nav-item">
                <a href="{{ cart_url }}" class="nav-link"><b>{{ request.session.cart_items }}</b><img src="https://tse1.mm.bing.net/th?id=OIP.l6nRvkoqnGh9tY1xJPK4LwHaGE&pid=Api&P=0&w=204&h=168" alt="cart" width="20px" height="20px"></a>
              </li>
          </ul>
          {% include 'snippets/search-form.html' %}
        </div> 
        </div>
      </nav>